### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by alonalibarmn** [Im2rnado/Carbide#1]
![image](https://user-images.githubusercontent.com/71559074/100114703-5f9dd880-2e7a-11eb-87f4-21aa9625255e.png)

**Comment by alonalibarmn** [comment]
bro i fix it and thare is so much thins cant be working
so much commends not working

**Comment by Im2rnado** [comment]
Updated it! Should work now. Just change shopv3 or shop

**Comment by Im2rnado** [comment]
Updated it! Just change shopv3 to shop
