### ISSUE TITLE
when i do +shop

### ISSUE THREAD

**Issue by alonalibarmn** [Im2rnado/Carbide#2]
(node:9048) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.fields[2].value: Must be 1024 or fewer in length.
    at RequestHandler.execute (F:\Desktop\Carbide-main (1)\Carbide-main\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by alonalibarmn** [comment]
when i do +locker
![image](https://user-images.githubusercontent.com/71559074/100116272-37af7480-2e7c-11eb-9407-3d15ec51d572.png)

**Comment by Im2rnado** [comment]
This is because the shop is too large to be put into a Discord Message. Please join our support server if you encounter any more issues: https://discord.gg/5pKvUpA

**Comment by Im2rnado** [comment]
I'll provide a fix for +locker in a few minutes so don't worry about it.
